# Generated by Django 2.0 on 2020-12-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, null=True, verbose_name='用户名')),
                ('mobile', models.CharField(max_length=11, null=True, verbose_name='手机号')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
