# Generated by Django 2.0 on 2020-12-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='password',
            field=models.CharField(max_length=100, null=True, verbose_name='密码'),
        ),
    ]
