# Generated by Django 2.0 on 2020-12-14 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_accountuser_password'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountuser',
            table='account_user',
        ),
    ]
