# Generated by Django 2.0 on 2020-12-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201214_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='password',
            field=models.CharField(max_length=200, null=True, verbose_name='密码'),
        ),
    ]
