# Generated by Django 3.0 on 2020-12-16 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201214_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authname', models.CharField(max_length=50, null=True, verbose_name='菜单名')),
                ('path', models.CharField(max_length=100, null=True, verbose_name='路径')),
                ('fatherid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Menus')),
            ],
            options={
                'verbose_name': '菜单栏',
                'verbose_name_plural': '菜单栏',
                'db_table': 'menus',
            },
        ),
    ]
