# Generated by Django 3.0 on 2020-12-16 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_menus'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='menu',
            field=models.ManyToManyField(null=True, to='account.Menus', verbose_name='菜单'),
        ),
        migrations.AlterField(
            model_name='menus',
            name='fatherid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Menus', verbose_name='父id'),
        ),
    ]
