# Generated by Django 3.0 on 2020-12-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20201216_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountuser',
            name='menu',
        ),
        migrations.AddField(
            model_name='menus',
            name='menu',
            field=models.ManyToManyField(to='account.AccountUser', verbose_name='菜单'),
        ),
    ]
