# Generated by Django 3.0 on 2020-12-16 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20201216_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 16, 15, 24, 17, 248125), null=True),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='mg_state',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='role_name',
            field=models.CharField(max_length=20, null=True, verbose_name='权限名称'),
        ),
    ]
